#ifndef _SKILLISSUEPACK_
#define _SKILLISSUEPACK_
#include <kamek.hpp>
#include <game/System/identifiers.hpp>
#include <game/UI/Ctrl/UIControl.hpp>
#include <File/Folder.hpp>

#define CUPCOUNT 38                    //46 MAX
#define TRACKCOUNT (CUPCOUNT * 4)      //184 max
#define TRACKBLOCKING 16




namespace CTTP{
const char modFolder[18] = "/CTTP";
const char ghostFolder[28] = "/CTTP/Ghosts";

extern u32 winningCourse;
const char UIAssets[15] = "/CTTPUI.szs";
const char CommonAssets[15] = "/CTTPCommon.szs";
const char breff[25] = "/Effect/CTTP.breff";
const char breft[26] = "/Effect/CTTP.breft";
const char controlFolder[8] = "control";
const char buttonFolder[7] = "button";
const char bgFolder[3] = "bg";

s32 Open(char *path, IOS::Mode mode);
CourseId GetCourseId();
void ChangeImage(LayoutUIControl *control, const char *paneName, const char *tplName);
const u8 extSlotToTrackId[CUPCOUNT][4] = {
{MOO_MOO_MEADOWS, GBA_BOWSER_CASTLE_3, KOOPA_CAPE, N64_BOWSERS_CASTLE},
{SNES_MARIO_CIRCUIT_3, RAINBOW_ROAD, GBA_SHY_GUY_BEACH, MAPLE_TREEWAY},
{DS_PEACH_GARDENS, DS_DESERT_HILLS, GBA_BOWSER_CASTLE_3, RAINBOW_ROAD},
{MUSHROOM_GORGE, DK_SUMMIT, N64_BOWSERS_CASTLE, GBA_BOWSER_CASTLE_3},
{SNES_GHOST_VALLEY_2, BOWSERS_CASTLE, BOWSERS_CASTLE, RAINBOW_ROAD},
{GBA_BOWSER_CASTLE_3, SNES_MARIO_CIRCUIT_3, KOOPA_CAPE, MOONVIEW_HIGHWAY},
{GCN_WALUIGI_STADIUM, MUSHROOM_GORGE, MARIO_CIRCUIT, RAINBOW_ROAD},
{BOWSERS_CASTLE, MOO_MOO_MEADOWS, TOADS_FACTORY, TOADS_FACTORY},
{SNES_GHOST_VALLEY_2, MAPLE_TREEWAY, RAINBOW_ROAD, MUSHROOM_GORGE},
{COCONUT_MALL, MARIO_CIRCUIT, MUSHROOM_GORGE, GCN_PEACH_BEACH},
{COCONUT_MALL, DRY_DRY_RUINS, DS_PEACH_GARDENS, WARIOS_GOLD_MINE},
{N64_SHERBET_LAND, KOOPA_CAPE, MOO_MOO_MEADOWS, DK_SUMMIT},
{RAINBOW_ROAD, DAISY_CIRCUIT, SNES_GHOST_VALLEY_2, N64_BOWSERS_CASTLE},
{GCN_MARIO_CIRCUIT, GCN_DK_MOUNTAIN, BOWSERS_CASTLE, GRUMBLE_VOLCANO},
{SNES_GHOST_VALLEY_2, RAINBOW_ROAD, TOADS_FACTORY, GRUMBLE_VOLCANO},
{SNES_GHOST_VALLEY_2, N64_SHERBET_LAND, GBA_SHY_GUY_BEACH, RAINBOW_ROAD},
{SNES_MARIO_CIRCUIT_3, GCN_WALUIGI_STADIUM, MARIO_CIRCUIT, RAINBOW_ROAD},
{N64_MARIO_RACEWAY, N64_BOWSERS_CASTLE, GRUMBLE_VOLCANO, MUSHROOM_GORGE},
{GRUMBLE_VOLCANO, DAISY_CIRCUIT, MARIO_CIRCUIT, MARIO_CIRCUIT},
{GRUMBLE_VOLCANO, DAISY_CIRCUIT, MARIO_CIRCUIT, MARIO_CIRCUIT},
{MUSHROOM_GORGE, DRY_DRY_RUINS, RAINBOW_ROAD, GRUMBLE_VOLCANO},
{GCN_WALUIGI_STADIUM, MUSHROOM_GORGE, MUSHROOM_GORGE, MUSHROOM_GORGE},
{MOONVIEW_HIGHWAY, SNES_GHOST_VALLEY_2, RAINBOW_ROAD, RAINBOW_ROAD},
{MAPLE_TREEWAY, N64_BOWSERS_CASTLE, KOOPA_CAPE, RAINBOW_ROAD},
{MUSHROOM_GORGE, RAINBOW_ROAD, RAINBOW_ROAD, RAINBOW_ROAD},
{RAINBOW_ROAD, N64_DKS_JUNGLE_PARKWAY, COCONUT_MALL, N64_DKS_JUNGLE_PARKWAY},
{MUSHROOM_GORGE, DS_DELFINO_SQUARE, DS_YOSHI_FALLS, DRY_DRY_RUINS},
{BOWSERS_CASTLE, DS_YOSHI_FALLS, KOOPA_CAPE, KOOPA_CAPE},
{MARIO_CIRCUIT, RAINBOW_ROAD, SNES_GHOST_VALLEY_2, SNES_MARIO_CIRCUIT_3},
{N64_BOWSERS_CASTLE, DK_SUMMIT, DRY_DRY_RUINS, MAPLE_TREEWAY},
{DS_PEACH_GARDENS, SNES_MARIO_CIRCUIT_3, SNES_GHOST_VALLEY_2, RAINBOW_ROAD},
{RAINBOW_ROAD, MARIO_CIRCUIT, MAPLE_TREEWAY, SNES_GHOST_VALLEY_2},
{DS_YOSHI_FALLS, RAINBOW_ROAD, DS_DESERT_HILLS, DRY_DRY_RUINS},
{SNES_MARIO_CIRCUIT_3, RAINBOW_ROAD, MARIO_CIRCUIT, GCN_MARIO_CIRCUIT},
{GRUMBLE_VOLCANO, GBA_BOWSER_CASTLE_3, MAPLE_TREEWAY, TOADS_FACTORY},
{GRUMBLE_VOLCANO, GCN_DK_MOUNTAIN, GRUMBLE_VOLCANO, GRUMBLE_VOLCANO},
{MARIO_CIRCUIT, KOOPA_CAPE, WARIOS_GOLD_MINE, MARIO_CIRCUIT},
{MAPLE_TREEWAY, DK_SUMMIT, MARIO_CIRCUIT, GCN_DK_MOUNTAIN},
};

const u8 extSlotToMusicSlot[CUPCOUNT][4] = {
{MOO_MOO_MEADOWS, GBA_BOWSER_CASTLE_3, KOOPA_CAPE, N64_BOWSERS_CASTLE},
{LUIGI_CIRCUIT, RAINBOW_ROAD, GBA_SHY_GUY_BEACH, DS_DESERT_HILLS},
{DS_PEACH_GARDENS, DS_DESERT_HILLS, GBA_BOWSER_CASTLE_3, RAINBOW_ROAD},
{N64_MARIO_RACEWAY, DK_SUMMIT, N64_BOWSERS_CASTLE, GBA_BOWSER_CASTLE_3},
{SNES_GHOST_VALLEY_2, BOWSERS_CASTLE, BOWSERS_CASTLE, BOWSERS_CASTLE},
{GBA_BOWSER_CASTLE_3, GRUMBLE_VOLCANO, DS_TWILIGHT_HOUSE, MOONVIEW_HIGHWAY},
{GCN_WALUIGI_STADIUM, MUSHROOM_GORGE, SNES_MARIO_CIRCUIT_3, GBA_BOWSER_CASTLE_3},
{BOWSERS_CASTLE, MOO_MOO_MEADOWS, TOADS_FACTORY, TOADS_FACTORY},
{SNES_GHOST_VALLEY_2, MAPLE_TREEWAY, RAINBOW_ROAD, MUSHROOM_GORGE},
{COCONUT_MALL, MOONVIEW_HIGHWAY, MUSHROOM_GORGE, GCN_PEACH_BEACH},
{RAINBOW_ROAD, MOONVIEW_HIGHWAY, DS_PEACH_GARDENS, WARIOS_GOLD_MINE},
{N64_SHERBET_LAND, GCN_PEACH_BEACH, MOO_MOO_MEADOWS, N64_SHERBET_LAND},
{DS_TWILIGHT_HOUSE, BLOCK_PLAZA, SNES_GHOST_VALLEY_2, N64_BOWSERS_CASTLE},
{GCN_MARIO_CIRCUIT, GCN_DK_MOUNTAIN, N64_BOWSERS_CASTLE, GRUMBLE_VOLCANO},
{SNES_GHOST_VALLEY_2, GCN_DK_MOUNTAIN, GCN_DK_MOUNTAIN, GRUMBLE_VOLCANO},
{SNES_GHOST_VALLEY_2, N64_SHERBET_LAND, GBA_SHY_GUY_BEACH, RAINBOW_ROAD},
{SNES_MARIO_CIRCUIT_3, GCN_WALUIGI_STADIUM, MOONVIEW_HIGHWAY, DAISY_CIRCUIT},
{DS_DELFINO_SQUARE, N64_BOWSERS_CASTLE, GRUMBLE_VOLCANO, GCN_MARIO_CIRCUIT},
{GRUMBLE_VOLCANO, DAISY_CIRCUIT, N64_MARIO_RACEWAY, TOADS_FACTORY},
{GRUMBLE_VOLCANO, DAISY_CIRCUIT, MARIO_CIRCUIT, DRY_DRY_RUINS},
{MUSHROOM_GORGE, DRY_DRY_RUINS, DS_PEACH_GARDENS, DS_DESERT_HILLS},
{GCN_WALUIGI_STADIUM, MUSHROOM_GORGE, MUSHROOM_GORGE, MUSHROOM_GORGE},
{MOONVIEW_HIGHWAY, SNES_GHOST_VALLEY_2, RAINBOW_ROAD, RAINBOW_ROAD},
{MAPLE_TREEWAY, N64_BOWSERS_CASTLE, KOOPA_CAPE, DS_PEACH_GARDENS},
{MUSHROOM_GORGE, RAINBOW_ROAD, RAINBOW_ROAD, RAINBOW_ROAD},
{RAINBOW_ROAD, N64_DKS_JUNGLE_PARKWAY, COCONUT_MALL, GCN_DK_MOUNTAIN},
{GCN_PEACH_BEACH, MOONVIEW_HIGHWAY, DS_YOSHI_FALLS, DRY_DRY_RUINS},
{BOWSERS_CASTLE, DS_YOSHI_FALLS, GCN_WALUIGI_STADIUM, BOWSERS_CASTLE},
{DS_YOSHI_FALLS, RAINBOW_ROAD, SNES_GHOST_VALLEY_2, SNES_MARIO_CIRCUIT_3},
{N64_BOWSERS_CASTLE, DK_SUMMIT, DRY_DRY_RUINS, MAPLE_TREEWAY},
{DS_PEACH_GARDENS, SNES_BATTLE_COURSE_4, SNES_GHOST_VALLEY_2, RAINBOW_ROAD},
{RAINBOW_ROAD, MARIO_CIRCUIT, MAPLE_TREEWAY, SNES_GHOST_VALLEY_2},
{DS_YOSHI_FALLS, RAINBOW_ROAD, DS_DESERT_HILLS, DRY_DRY_RUINS},
{COCONUT_MALL, GRUMBLE_VOLCANO, WARIOS_GOLD_MINE, GCN_MARIO_CIRCUIT},
{GRUMBLE_VOLCANO, GBA_BOWSER_CASTLE_3, MAPLE_TREEWAY, TOADS_FACTORY},
{DS_TWILIGHT_HOUSE, GCN_DK_MOUNTAIN, GRUMBLE_VOLCANO, GRUMBLE_VOLCANO},
{MOONVIEW_HIGHWAY, KOOPA_CAPE, WARIOS_GOLD_MINE, RAINBOW_ROAD},
{SNES_GHOST_VALLEY_2, DK_SUMMIT, DAISY_CIRCUIT, N64_DKS_JUNGLE_PARKWAY},
};


}//namespace SIP
#endif